//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyTravelMonitoringApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTravelMonitoring
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public string ScheduleRemark { get; set; }
        public string VehicleType { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> StartKmReading { get; set; }
        public Nullable<int> EndKmReading { get; set; }
        public Nullable<int> TotalKmTravelled { get; set; }
        public Nullable<decimal> RatePerKm { get; set; }
        public Nullable<decimal> TotalTravelCost { get; set; }
        public Nullable<decimal> MeetingExpenses { get; set; }
        public Nullable<decimal> StayExpenses { get; set; }
        public Nullable<decimal> FoodExpenses { get; set; }
        public string DayFinalRemarks { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public Nullable<System.Guid> IDGuid { get; set; }
        public string C_FileName { get; set; }
        public string C_Extension { get; set; }
        public Nullable<System.Guid> C_IDGuid { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
