//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyTravelMonitoringApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelingTeam_DB_Context : DbContext
    {
        public TravelingTeam_DB_Context()
            : base("name=TravelingTeam_DB_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<UserRolesMapping> UserRolesMappings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<DailyTravelMonitoring> DailyTravelMonitorings { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FileDetail> FileDetails { get; set; }
    }
}
